project_id = "zlmmflrlkvzvcaxuokhx"

[functions.send-invite]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.add-member]
verify_jwt = false

[functions.notify-push]
verify_jwt = false
